services:
  nodecg:
    build:
      context: .
      args:
        BINGOTHON_LAYOUTS_BRANCH: ${BINGOTHON_LAYOUTS_BRANCH:-master}
        UID: ${DOCKER_UID:-1000}
        GID: ${DOCKER_GID:-1000}
    user: "${DOCKER_UID:-1000}:${DOCKER_GID:-1000}"
    ports:
      - "9090:9090"
    volumes:
      - nodecg-logs:/opt/nodecg/logs
      - nodecg-db:/opt/nodecg/db
      - nodecg-assets:/opt/nodecg/assets
      - ./bundles:/opt/nodecg/bundles
    restart: unless-stopped
    environment:
      - NODECG_ROOT=/opt/nodecg
    networks:
      - bingothon-network

volumes:
  nodecg-logs:
  nodecg-db:
  nodecg-assets:

networks:
  bingothon-network:
    external: true
